### ISSUE TITLE
Not Working in VS 2013

### ISSUE THREAD

**Issue by ssinno28** [mirik123/tfsprod#6]
Hello,

For some reason when I initially tried installing TFS Productivity tools it said that the framework that it is dependent on was missing (4.5.1). I have 4.6.1 installed as well as all older frameworks. I ended up modifying the extension manifest and got it to install. Now I'm dealing with an issue where the toolbar and menu items are missing.

Is this extension compatible with VS 2013? The screen shots are definitely from older versions.

**Comment by mirik123** [comment]
It can be installed on VS2015 but still uses libraries from VS2012, so you will need to have 2 versions installed plus possibly also TFS SDK and VS SDK.

**Comment by ssinno28** [comment]
Yeah still doesn't seem to be working, here is the logs:

12/10/2016 1:18:18 PM - Microsoft VSIX Installer
12/10/2016 1:18:18 PM - -------------------------------------------
12/10/2016 1:18:18 PM - Initializing Install...
12/10/2016 1:18:18 PM - Extension Details...
12/10/2016 1:18:18 PM -               Identifier      : 16bf0a1d-6239-485f-ac25-6fcd37d514c7
12/10/2016 1:18:18 PM -               Name            : TFS Productivity Tools
12/10/2016 1:18:18 PM -               Author          : Mark Babayev
12/10/2016 1:18:18 PM -               Version         : 2.1.0
12/10/2016 1:18:18 PM -               Description     : The TFS Productivity Tools project was designed to provide TFS administrators with helper extensions for Source Control or Work Item Tracking tasks.
12/10/2016 1:18:18 PM -               Locale          : en-US
12/10/2016 1:18:18 PM -               MoreInfoURL     : https://github.com/mirik123/tfsprod
12/10/2016 1:18:18 PM -               InstalledByMSI  : False
12/10/2016 1:18:18 PM -               SupportedFrameworkVersionRange : [4.5]
12/10/2016 1:18:18 PM - 
12/10/2016 1:18:18 PM -               Supported Products : 
12/10/2016 1:18:18 PM -                               Microsoft.VisualStudio.Pro
12/10/2016 1:18:18 PM -                                               Version : [11.0,14.0]
12/10/2016 1:18:18 PM - 
12/10/2016 1:18:18 PM -               References      : 
12/10/2016 1:18:18 PM -                               -------------------------------------------------------
12/10/2016 1:18:18 PM -                               Identifier   : Microsoft.VisualStudio.MPF.11.0
12/10/2016 1:18:18 PM -                               Name         : Visual Studio MPF 11.0
12/10/2016 1:18:18 PM -                               Version      : [11.0]
12/10/2016 1:18:18 PM -                               MoreInfoURL  :
12/10/2016 1:18:18 PM -                               Nested       : No
12/10/2016 1:18:18 PM - 
12/10/2016 1:18:18 PM - 
12/10/2016 1:18:18 PM - Searching for applicable products...
12/10/2016 1:18:18 PM - Found installed product - Microsoft Visual Studio Professional 2012
12/10/2016 1:18:19 PM - The extension with ID '16bf0a1d-6239-485f-ac25-6fcd37d514c7' is not installed to Microsoft Visual Studio Professional 2012.
12/10/2016 1:18:19 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
12/10/2016 1:18:19 PM - Found installed product - Microsoft Visual Studio Professional 2013
12/10/2016 1:18:19 PM - The extension with ID '16bf0a1d-6239-485f-ac25-6fcd37d514c7' is not installed to Microsoft Visual Studio Professional 2013.
12/10/2016 1:18:19 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12/10/2016 1:18:19 PM - Found installed product - Global Location
12/10/2016 1:18:21 PM - The following target products have been selected...
12/10/2016 1:18:21 PM -               Microsoft Visual Studio Professional 2012
12/10/2016 1:18:21 PM -               Microsoft Visual Studio Professional 2013
12/10/2016 1:18:21 PM - 
12/10/2016 1:18:21 PM - Beginning to install extension to Microsoft Visual Studio Professional 2012...
12/10/2016 1:18:21 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'TFS Productivity Tools' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
12/10/2016 1:18:22 PM - Beginning to install extension to Microsoft Visual Studio Professional 2013...
12/10/2016 1:18:22 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'TFS Productivity Tools' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
